Database:
  Tipo: SQLITE #Tipos: MYSQL, SQLITE
  IP: localhost:3306
  DB: test
  User: admin
  Pass: ''
  Debug: true

# Comandos e aliases do plugin
Comando:
  Comando: 'loja'
  Aliases: [ ]
  Anunciar:
    Comando: 'anunciar'
    Aliases: [ ]

# Preco para criacao da loja
Precos:
  preco1:
    provider: 'money'
    amount: 1000.0

# Mundos em que poderá setar uma loja
Mundos permitidos:
  - 'world'
  - 'plot'

# Somente permitir loja no plot? (PlotSquared)
Somente plot: true

# Permissão (ylojas.gratis)
# Ativar a permissão para criar lojas gratuitamente
Permissao gratis: true

# Quantia de letras que o nome da loja pode ter.
Nome quantia: 15

# Quantia de letras que a descrição da loja pode ter.
Desc quantia: 20

# Em segundos ( delay para anunciar a loja )
Delay: 60

# Tag do jogador com a loja mais visitada
Tag: '&5[SHOP]'

# Fechar lojas as quais os jogadores logaram há mais de x tempo
# em segundos
# Deixe 0 para não usar
Tempo off fechar: 2592000

# Mensagens do plugin
Mensagens:
  Permissao: '&c&lERRO! &cVocê não tem permissão para isto.'
  Permissao criar: '&c&lERRO! &cVocê não tem permissão para criar uma loja.'
  Deletada: '&a&lSUCESSO! &aVocê deletou sua loja com sucesso.'
  Local setado: '&a&lSUCESSO! &aVocê setou o local da tua loja.'
  Local removido: '&a&lSUCESSO! &aVocê removeu o local da tua loja.'
  Teleportado: '&a&lSUCESSO! &aVocê foi teleportado.'
  Cancelou: '&cVocê cancelou a ação.'
  Nome quantia: '&c&lERRO! &cO nome da loja não pode ser menor que 1 caractere ou maior que 15 caracteres.'
  Desc quantia: '&c&lERRO! &cA descrição da loja não pode ser menor que 1 caractere ou maior que 20 caracteres.'
  Mudou nome: '&a&lSUCESSO! &aAgora o nome da tua loja é: &7{nome}&a.'
  Mudou desc: '&a&lSUCESSO! &aAgora a descrição da tua loja é: &7{desc}&a.'
  Local primeiro: '&c&lERRO! &cVocê deve setar o local da loja primeiro.'
  Removeu avaliacao: '&a&lSUCESSO! &aVocê removeu sua avaliação.'
  Avaliacao positiva: '&a&lSUCESSO! &aVocê avaliou positivamente a loja.'
  Avaliacao negativa: '&a&lSUCESSO! &aVocê avaliou negativamente a loja.'
  Avaliar si mesmo: '&c&lERRO! &cVocê não pode avaliar sua própria loja.'
  Nao encontrado: '&c&lERRO! &cJogador não encontrado.'
  Nao possui: '&c&lERRO! &cEste jogador não possui loja.'
  Fechada: '&c&lERRO! &cEsta loja está fechada.'
  Mundo: '&cMundo não permitido.'
  Terreno: '&cVocê não tem permissão neste terreno.'
  Delay: '&cVocê deve aguadar {tempo} para anunciar sua loja novamente.'
  Anunciar sem: '&cVocê não tem uma loja para anunciar.'
  Anunciar fechada: '&cVocê não pode anunciar sua loja estando fechada.'
  Nao tem: '&cVocê não possui uma loja.'
  No-balance: '&cVocê não tem {provider_display} suficiente para isto. Disponível: {provider_balance}&c.'
  Digite nome:
    - ''
    - '&aDigite o nome da loja.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Digite desc:
    - ''
    - '&aDigite o nome da descrição.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Help:
    - '&c-> Comandos disponíveis <-'
    - ''
    - ' &f> &c/loja'
    - ' &f> &c/loja anunciar'
    - ' &f> &c/loja desfazer'
    - ' &f> &c/loja avaliar'
    - ' &f> &c/loja setar'
    - ' &f> &c/loja <player>'

# Setas dos menus
Setas:
  Voltar:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&cVoltar'
    Lore:
      - ''
      - '&7Clique para voltar.'
      - ''
  Anterior:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&aPróximo'
    Lore:
      - ''
      - '&7Clique para ir à página anterior.'
      - ''
  Proximo:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&aPróximo'
    Lore:
      - ''
      - '&7Clique para ir à próxima página.'
      - ''

# Formatador booleano e de mensagens
Formatador:
  True f: '&aSim'
  False f: '&cNão'
  Sem nome: '&7Sem nome.'
  Sem desc: '&7Sem descrição.'

# Formatos de money e quantia
Formats:
  - ''
  - ''
  - 'K'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'O'
  - 'N'
  - 'D'